/* Generated using SQL generator */

DROP SCHEMA library CASCADE;
CREATE SCHEMA library;

create sequence library.books_id_seq;

alter sequence library.books_id_seq owner to pgbqmord;

create sequence library.authors_id_seq;

alter sequence library.authors_id_seq owner to pgbqmord;

create sequence library.user_id_seq;

alter sequence library.user_id_seq owner to pgbqmord;

create sequence library.books_book_id_seq
    as integer;

alter sequence library.books_book_id_seq owner to pgbqmord;

create sequence library.authors_author_id_seq
    as integer;

alter sequence library.authors_author_id_seq owner to pgbqmord;

create sequence library.end_users_end_user_id_seq
    as integer;

alter sequence library.end_users_end_user_id_seq owner to pgbqmord;

create table library.books
(
    book_id       integer generated by default as identity,
    title         text,
    publisher     text,
    cover_img_url text,
    primary key (book_id)
);

alter table library.books
    owner to pgbqmord;

alter sequence library.books_id_seq owned by library.books.book_id;

create index books_id_title_index
    on library.books (book_id, title);

create table library.authors
(
    author_id   integer generated by default as identity,
    name        text,
    birthday    date,
    nationality text,
    primary key (author_id)
);

alter table library.authors
    owner to pgbqmord;

alter sequence library.authors_id_seq owned by library.authors.author_id;

create index authors_author_id_name_index
    on library.authors (author_id, name);

create table library.author_wrote_book_items
(
    book_id   integer not null,
    author_id integer not null,
    constraint compositekey
        primary key (book_id, author_id),
    constraint fk_book
        foreign key (book_id) references library.books
            on delete cascade,
    constraint fk_author
        foreign key (author_id) references library.authors
            on delete cascade
);

alter table library.author_wrote_book_items
    owner to pgbqmord;

create table library.end_users
(
    email           text not null,
    status          text,
    end_user_id     integer generated always as identity,
    password_hash   text not null,
    salt            text not null,
    role            text,
    profile_img_url integer,
    constraint user_pk
        primary key (end_user_id)
);

alter table library.end_users
    owner to pgbqmord;

alter sequence library.user_id_seq owned by library.end_users.end_user_id;

create table library.reading_list_items
(
    user_id integer not null,
    book_id integer not null,
    constraint reading_list_items_pk
        primary key (book_id, user_id),
    constraint readinglistitems_user_id_fk
        foreign key (user_id) references library.end_users
            on delete cascade,
    constraint readinglistitems_books_id_fk
        foreign key (book_id) references library.books
            on delete cascade
);

alter table library.reading_list_items
    owner to pgbqmord;

